[package]
name = "treeview"
version = "0.1.0"
authors = ["ivy <ivy.rice.seo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
glib = "0.10.3"
